# Site configuration for crm3.local
db_host: 127.0.0.1
db_port: 3306
db_name: crm3_db
db_user: root
db_password: kora123

redis_url: redis://localhost:6379/0

file_storage: local
files_path: sites/crm3.local/files

apps:
  - core

hostname: crm3.local
