name: Job Lifecycle
document_type: Job Opening
is_active: true
workflow_state_field: status
states:
  - state: Open
    doc_status: 0
    allow_edit: Recruiter, Administrator
    style: success
  - state: Interviewing
    doc_status: 0
    allow_edit: Recruiter, Administrator
    style: warning
  - state: Offer Extended
    doc_status: 0
    allow_edit: Recruiter, Administrator
    style: info
  - state: Filled
    doc_status: 1
    allow_edit: ""
    style: default
  - state: Cancelled
    doc_status: 2
    allow_edit: ""
    style: danger
transitions:
  - action: Start Interviews
    from: Open
    to: Interviewing
    allowed: Recruiter, Administrator
  - action: Extend Offer
    from: Interviewing
    to: Offer Extended
    allowed: Recruiter, Administrator
  - action: Fill Position
    from: Offer Extended
    to: Filled
    allowed: Recruiter, Administrator
  - action: Cancel
    from: Open
    to: Cancelled
    allowed: Recruiter, Administrator
  - action: Cancel
    from: Interviewing
    to: Cancelled
    allowed: Recruiter, Administrator
