- doctype: Property
  role: Property Manager
  can_read: true
  can_write: true
  can_create: true
  can_delete: false
- doctype: Property
  role: Administrator
  can_read: true
  can_write: true
  can_create: true
  can_delete: true
- doctype: Lease
  role: Property Manager
  can_read: true
  can_write: true
  can_create: true
  can_delete: true
- doctype: Lease
  role: Administrator
  can_read: true
  can_write: true
  can_create: true
  can_delete: true
