- doctype: Course
  role: Instructor
  can_read: true
  can_write: true
  can_create: true
  can_delete: false
- doctype: Course
  role: Administrator
  can_read: true
  can_write: true
  can_create: true
  can_delete: true
- doctype: Lesson
  role: Instructor
  can_read: true
  can_write: true
  can_create: true
  can_delete: true
- doctype: Lesson
  role: Administrator
  can_read: true
  can_write: true
  can_create: true
  can_delete: true
- doctype: Enrollment
  role: Instructor
  can_read: true
  can_write: true
  can_create: true
  can_delete: true
- doctype: Enrollment
  role: Administrator
  can_read: true
  can_write: true
  can_create: true
  can_delete: true
