# Site configuration for inventory.local
db_host: 127.0.0.1
db_port: 3306
db_name: inventory_db
db_user: root
db_password: kora123

redis_url: redis://localhost:6379/0

file_storage: local
files_path: sites/inventory.local/files

apps:
  - core

hostname: inventory.local
