# Site configuration for lms2.local
db_host: 127.0.0.1
db_port: 3306
db_name: lms2_db
db_user: root
db_password: kora123

redis_url: redis://localhost:6379/0

file_storage: local
files_path: sites/lms2.local/files

apps:
  - core

hostname: lms2.local
